global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, alertmanager, etc.)
  external_labels:
    monitor: 'rentdrive-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself and our RentDrive application.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rentdrive-app'
    metrics_path: '/api/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:3000']
